### ISSUE TITLE
env handling in deployement.yaml

### ISSUE THREAD

**Issue by yelhouti** [jenkins-x/jxr-packs-kubernetes#54]
Hi, may I suggest to switching to the standard handling of env variables in our deployment.yaml:
```
        env:
{{- if .Values.env }}
{{ toYaml .Values.env | indent 10 }}
{{- end }}
```
instead of the loop
```
{{- range $pkey, $pval := .Values.env }}
        - name: {{ $pkey }}
          value: {{ quote $pval }}
{{- end }}
```
that prevent complicated env vars from config or secrets like:
```
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.how
```

I'm doing this manually for all my charts... thanks in advance.
